NumPy uses ndarray → N-dimensional array.

In [2]:
import numpy as np
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

Array Types

In [7]:
arr=np.array([1,2,3],dtype=complex)
print(arr)
#You can force type (int, float, complex)

[1.+0.j 2.+0.j 3.+0.j]


Special Arrays                                                   
                   Useful for initializing data quickly.

In [10]:
zeros = np.zeros((2,3))      # 2x3 array of 0s
ones = np.ones((2,3))        # 2x3 array of 1s
range_arr = np.arange(0, 10, 2)  # start, stop, step
linspace_arr = np.linspace(0, 1, 5) # equally spaced numbers
print(zeroes)
print(ones)
print(range_arr)
print(linspace_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


Array Properties                    
                                                                  Helps understand the structure before processing.
 


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # rows, columns
print(arr.ndim)    # number of dimensions
print(arr.size)    # total elements
print(arr.dtype)   # data type

(2, 3)
2
6
int32


Indexing & Slicing

In [18]:
arr = np.array([10, 20, 30, 40])
print(arr[1])      # single element
print(arr[1:3])    # slice
print(arr[-1])     # last element


20
[20 30]
40


Multi-Dimensional Indexing

In [59]:
arr = np.array([[1,2],[4,5],[6,7]])
print(arr[0,1])   # row 0, col 1 → 2
print(arr[:,1])   # all rows, col 1 → [2 5]


2
[2 5 7]


array([[1],
       [2],
       [4],
       [5],
       [6],
       [7]])

Conversion of 1D array To 2D array  
 Total Elements Must Stay the Same
If your 1D array has N elements, your new 2D shape must multiply to N.      
arr.reshape(2, -1)    [Used in Industry,Let numpy figure it out]


In [67]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
array.reshape(2,-1)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Resize  
During Resizingnumpy append zeros if a value is missing  
Ex-Resizing 1x6 array to 2x3 and 3x4


In [17]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr1.resize((2,3))
print(arr1)
print("\n")
arr1.resize((3,4))
print(arr1)



[[1 2 3]
 [4 5 6]]


[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


Vectorized Operations  
Concept: Applies operations on entire array at once  
Why? Faster than loops , Runs in C internally

In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Sqaure",a**b)

Addition [5 7 9]
Subtraction [-3 -3 -3]
Multiplication [ 4 10 18]
Sqaure [  1  32 729]


Broadcasting   
Concept:Numpy "Stretches" array so shapes match  
Why? No need for manual loops to match shape

In [20]:
arr=np.array([[1,2,3],
              [4,5,6]])
arr1=np.array([10,20,30])
#Broadcast arr1 to match arr
print(arr+arr1)

[[11 22 33]
 [14 25 36]]


Boolean Indexing and Masks   
Concept:Filter data with conditions

In [24]:
arr=np.array([5,10,15,20,25,30])
mask=arr>15
print(mask) #Boolean array (True or False...)
print(arr[mask]) #Filtered Values

[False False False  True  True  True]
[20 25 30]


Math & Statistics  
Concept: Quick calculations along rows/columns.   
axis=0(Column)  
axis=1(Row)



In [11]:
data=np.array([[1,2,3],
              [4,5,6]])
print(data.sum())
print(data.mean())
print(data.sum(axis=0)) #sum of each column
print(data.sum(axis=1)) #sum of each row
print(data.max())
print(data.min())


21
3.5
[5 7 9]
[ 6 15]
6
1


Reshape, Flatten, Ravel   
Concept: Change dimensions or make 1D.

In [20]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.reshape(3,2)) # change shape
print(arr.reshape(6,1)) # change shape
print(arr.ravel())  # returns view (faster)
print(arr.flatten()) # returns copy

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


Stacking & Splitting  
Concept: Join or split arrays.   
✅ Why? Used in merging datasets, splitting features/labels.



In [35]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.vstack((a,b))  # vertical stack
print(c)
d=np.hstack((a,b)) # horizontal stack
print(d)
print(np.hsplit(a,1)) # split into 2 columns
print("\n vstack/hstack are more readable")
print(np.concatenate((a, b), axis=1))
print(np.concatenate((a, b), axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2],
       [3, 4]])]

 vstack/hstack are more readable
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [36]:
import numpy as np

# Numeric features
X_numeric = np.array([[25, 170], [30, 180], [22, 165]])  # age, height

# Categorical (Gender)
X_gender = np.array(['Male', 'Female', 'Male'])

# One-hot encode gender manually
X_gender_encoded = np.array([[1, 0], [0, 1], [1, 0]])  # [Male, Female]

# Combine numeric + encoded categorical
X_full = np.hstack((X_numeric, X_gender_encoded))
print(X_full)


[[ 25 170   1   0]
 [ 30 180   0   1]
 [ 22 165   1   0]]


In [ ]:
X_numeric=np.array([[10,20],[14,20],[40,06]])
X_gender=np.array([''])

In [10]:
a=[[1,2,3]
  ,[4,5,6]]
a[::-2]

[[4, 5, 6]]

In [2]:
import numpy as np
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[::2])
#::2 here means:
#Start at row 0
#Go until the end
#Step = 2
#So it picks row 0, row 2 (skips row 1).
#:2 → "up to column index 2 (exclusive)"

#::2 → "every 2nd column"
print("\n")
print(A[:,:2]) 

[['a' 'b' 'c']
 ['g' 'h' 'i']]


[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In NumPy slicing:  
: alone → means “take everything” along that axis.  
:: → same as :, but lets you add a step.  
::2 → take every 2nd element.  
::-1 → reverse order.Shapes:  
  
A[...] has two axes (rows, columns).  
If you write one thing inside [], like A[::2], you’re only slicing rows (the first axis). Columns are assumed as "all".  
If you write two things, like A[:, ::2], then:   
first part (before comma) → row selection 
second part (after comma) → column selection

In [29]:
A = np.array([
    ['a','b','c'],
    ['d','e','f'],
    ['g','h','i']
])
print(A[::2]) #A[::2] → rows 0 and 2
print("\n")
print(A[:, ::2])  # all rows, every 2nd column
print("\n")
print(A[:, :2]) # → all rows, columns 0 and 1
print("\n")
print(A[:1:])

[['a' 'b' 'c']
 ['g' 'h' 'i']]


[['a' 'c']
 ['d' 'f']
 ['g' 'i']]


[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


[['a' 'b' 'c']]


In [3]:
a = np.arange(5)
a + 20

array([20, 21, 22, 23, 24])

🔹 Linear Algebra with NumPy

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A.T) # Transpose - flips rows ↔ columns
print(B.T)


[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [21]:
print(A+B,A-B,A@B,A*B)
#Identity MAtrix
I = np.eye(3)  
print(I)
print(np.linalg.inv(A)) #INverse
print(np.linalg.det(A)) #Determminant to check invertibility det =0 is not invertible
print(np.linalg.matrix_rank(A)) # To check number of independent rows/columns
print(np.trace(A)) # Sum of diagonal elements
vals,vec= np.linalg.eig(A)
#Core in ML: PCA, spectral clustering etc
#Solving Linear Equations
#Equation: Ax = b
A = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(A, b)
print(x)

[[ 6  8]
 [10 12]] [[-4 -4]
 [-4 -4]] [[19 22]
 [43 50]] [[ 5 12]
 [21 32]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
2
5
[2. 3.]


# Useful Functions

In [32]:
#1. np.arange()
#Creates evenly spaced values (like Python range() but gives a NumPy array).
A=np.arange(0,20,2)
A

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
#np.linspace()
# 👉 Creates evenly spaced values between two numbers, with a fixed count of points.
b = np.linspace(0, 1, 5)   # start=0, stop=1, 5 values
print(b)   # [0.   0.25 0.5  0.75 1. ]
  

[0.   0.25 0.5  0.75 1.  ]


In [40]:
#np.random ( Generates random numbers)
import numpy as np
# 1. Random integers in a range
rand_ints = np.random.randint(1, 10, size=(2, 3))  
print("Random Integers:\n", rand_ints)

# 2. Random floats between 0 and 1
rand_floats = np.random.rand(2, 2)  
    # 2x2 array with values in [0, 1)
print("\nRandom Floats (0-1):\n", rand_floats)

# 3. Random numbers from Standard Normal Distribution (mean=0, std=1)
rand_normal = np.random.randn(3)  
print("\nRandom Normal Distribution:\n", rand_normal)

# 4. Random choice from a list/array
rand_choice = np.random.choice([10, 20, 30, 40], size=10)  
print("\nRandom Choice:\n", rand_choice)

# 5. Shuffle an array in place
arr = np.arange(10)
np.random.shuffle(arr)  
# Randomly shuffles the array
print("\nShuffled Array:\n", arr)


Random Integers:
 [[9 6 7]
 [9 4 6]]

Random Floats (0-1):
 [[0.54493653 0.64270624]
 [0.44265534 0.22782314]]

Random Normal Distribution:
 [-0.07443227  0.41860743  0.11232603]

Random Choice:
 [10 20 10 10 30 20 30 20 10 40]

Shuffled Array:
 [8 4 1 2 9 6 5 3 0 7]
